[package]
name = "gmac_core"
description = "Core geometry functionality."
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[lib]
name = "gmac_core"
path = "src/lib.rs"
test = true
doctest = false

[dependencies]
